CREATE TABLE TRAINER(ID INT PRIMARY KEY, FIRST_NAME VARCHAR(255), SURNAME VARCHAR(255));
INSERT INTO TRAINER VALUES (1, 'John', 'Gordon');
INSERT INTO TRAINER VALUES (2, 'Chris', 'Perrins');
INSERT INTO TRAINER VALUES (3, 'Matt', 'Hunt');
INSERT INTO TRAINER VALUES (4, 'Jay', 'Grindrod');
INSERT INTO TRAINER VALUES (5, 'Bob', 'Crutchley');
DROP TABLE TRAINER;